using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NestedObjects
{
    public class Student
    {
        /// <summary>
        /// this number is generated by the DB
        /// </summary>
        public int StudentID { get; set; }

        /// <summary>
        /// the first and alst name of the student ex. Kyran Perdue
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// the date the student was born
        /// time is ignored
        /// </summary>
        public DateTime? DateOfBirth { get; set; }
    }
}
